#!/usr/bin/env python3
import json
from pathlib import Path

m = json.loads(Path("projekt-manifest.json").read_text(encoding="utf-8"))
errors = []
if m.get("schema_version") != 1: errors.append("Manifest-schema_version muss 1 sein")
app = m.get("app", {})
if app.get("version") != "0.2.1": errors.append("App-Version muss 0.2.1 sein")
iteration = m.get("iteration", {})
if iteration.get("number") != 2: errors.append("Iteration muss 2 sein")
if iteration.get("stage") != "2.1": errors.append("Iterationsstufe muss 2.1 sein")
if iteration.get("release") != "0.2.1": errors.append("Release muss 0.2.1 sein")
ui = m.get("ui", {})
if ui.get("areas") != list("ABCDEFGHIJKLMN"): errors.append("A-N-Bereiche unvollständig")
if len(ui.get("themes", [])) != 5: errors.append("genau fünf Themes erforderlich")
quality = m.get("quality", {})
if quality.get("manual_user_acceptance_required") is not False: errors.append("manuelle Nutzerabnahme muss false sein")
if quality.get("crash_recovery_tests") is not True: errors.append("Crash-/Recovery-Tests müssen aktiv sein")
if quality.get("self_repair_guarded") is not True: errors.append("Self-Repair muss geschützt sein")
if quality.get("risk_model") != "R0-R4": errors.append("Risikomodell muss R0-R4 sein")
if quality.get("agent_contract_validation") != "scripts/validate_agents.py": errors.append("Agentenvertragsprüfung fehlt")
backup = m.get("backup", {})
if backup.get("keep_previous") != 2: errors.append("zwei Git-Vorgängerversionen erforderlich")
if backup.get("database_verified_keep") != 2: errors.append("zwei verifizierte DB-Sicherungen erforderlich")
data = m.get("data", {})
if data.get("engine") != "sqlite3": errors.append("Datenkern muss sqlite3 sein")
if data.get("schema_version") != 1: errors.append("DB-Schema muss 1 sein")
if data.get("journal_mode") != "WAL": errors.append("SQLite-WAL erforderlich")
if data.get("calendar_source") != "todos": errors.append("Kalender muss aus Todos gespeist werden")
if data.get("archive_strategy") != "logical-reversible": errors.append("Todo-Archiv muss reversibel sein")
if data.get("backup_keep") != 2: errors.append("DB-Backup-Retention muss 2 sein")
agents = m.get("agents", {})
required_agents = {"analysis", "risk", "root_cause", "planning", "regression", "compliance", "release"}
if set(agents) != required_agents: errors.append("Manifest muss exakt sieben definierte Prüfrollen enthalten")
self_repair = m.get("self_repair", {})
allowed = self_repair.get("automatic_scope", [])
forbidden = self_repair.get("forbidden_scope", [])
if not isinstance(allowed, list) or len(allowed) < 4: errors.append("Self-Repair-Allowlist ist unvollständig")
if not isinstance(forbidden, list) or len(forbidden) < 6: errors.append("Self-Repair-Denylist ist unvollständig")
if "delete-user-data" not in forbidden or "restore-unverified-backup" not in forbidden: errors.append("kritische Self-Repair-Verbote fehlen")
error_handling = m.get("error_handling", {})
if error_handling.get("stable_api_codes") is not True: errors.append("stabile API-Fehlercodes müssen aktiv sein")
if error_handling.get("unknown_internal_details_exposed") is not False: errors.append("interne Fehlerdetails dürfen nicht exponiert werden")
if errors:
    for error in errors: print("FEHLER:", error)
    raise SystemExit(1)
print("OK   Manifest konsistent – v0.2.1 Reliability & Self-Repair")
