#!/usr/bin/env python3
import json
from pathlib import Path
m=json.loads(Path('projekt-manifest.json').read_text(encoding='utf-8')); errors=[]
if m.get('schema_version')!=1: errors.append('Manifest-schema_version muss 1 sein')
app=m.get('app',{})
if app.get('version')!='0.2.2': errors.append('App-Version muss 0.2.2 sein')
it=m.get('iteration',{})
if it.get('number')!=2 or it.get('stage')!='2.2' or it.get('release')!='0.2.2': errors.append('Iteration 2.2 / Release 0.2.2 erforderlich')
ui=m.get('ui',{})
if ui.get('areas')!=list('ABCDEFGHIJKLMN'): errors.append('A-N-Bereiche unvollständig')
if len(ui.get('themes',[]))!=5: errors.append('genau fünf Themes erforderlich')
if ui.get('font_scale_percent',{}).get('max')!=200: errors.append('Schriftskalierung muss bis 200 % reichen')
if ui.get('high_contrast') is not True: errors.append('Kontrast+ muss aktiv sein')
if ui.get('global_feedback') is not True: errors.append('globale Feedbackschicht fehlt')
if ui.get('process_counters')!=['ok','warn','error','skipped']: errors.append('Prozesszähler unvollständig')
if ui.get('screenreader_live_status') is not True or ui.get('skip_link') is not True: errors.append('Accessibility-Vertrag unvollständig')
q=m.get('quality',{})
if q.get('manual_user_acceptance_required') is not False: errors.append('manuelle Nutzerabnahme muss false sein')
if q.get('crash_recovery_tests') is not True or q.get('self_repair_guarded') is not True: errors.append('Recovery-/Self-Repair-Schutz fehlt')
if q.get('risk_model')!='R0-R4' or q.get('agent_contract_validation')!='scripts/validate_agents.py': errors.append('Agenten-/Risikovertrag fehlt')
if q.get('ux_contract_test')!='tests/test_ux_contract.py': errors.append('UX-Vertragstest fehlt')
b=m.get('backup',{})
if b.get('keep_previous')!=2 or b.get('database_verified_keep')!=2: errors.append('zwei Git- und DB-Rückfallstände erforderlich')
d=m.get('data',{})
if d.get('engine')!='sqlite3' or d.get('schema_version')!=1 or d.get('journal_mode')!='WAL': errors.append('SQLite-Datenvertrag ungültig')
if d.get('calendar_source')!='todos' or d.get('archive_strategy')!='logical-reversible' or d.get('backup_keep')!=2: errors.append('Datenkern-Verträge unvollständig')
required_agents={'analysis','risk','root_cause','planning','regression','compliance','release'}
if set(m.get('agents',{}))!=required_agents: errors.append('Manifest muss exakt sieben Prüfrollen enthalten')
sr=m.get('self_repair',{})
if len(sr.get('automatic_scope',[]))<4 or len(sr.get('forbidden_scope',[]))<6: errors.append('Self-Repair-Vertrag unvollständig')
if 'delete-user-data' not in sr.get('forbidden_scope',[]) or 'restore-unverified-backup' not in sr.get('forbidden_scope',[]): errors.append('kritische Self-Repair-Verbote fehlen')
eh=m.get('error_handling',{})
if eh.get('stable_api_codes') is not True or eh.get('unknown_internal_details_exposed') is not False: errors.append('Fehlerbehandlungsvertrag ungültig')
if errors:
    [print('FEHLER:',e) for e in errors]; raise SystemExit(1)
print('OK   Manifest konsistent – v0.2.2 UX, Feedback & Transparenz')
